### ISSUE TITLE
Class Diagram – Horizontal lines don't work

### ISSUE THREAD

**Issue by 174n** [aduh95/yuml2svg#3]
I use this code and I don't see the horizontal line
```yuml
[Creator|+factoryMethod():Product;]^-[ConcreteCreator|+factoryMethod():Product;]
```

It should look like this:
![yuml.me](https://yuml.me/diagram/scruffy/class/[Creator|+factoryMethod():Product;]^-[ConcreteCreator|+factoryMethod():Product;])

But it looks like this:
![yuml2svg](http://i.imgur.com/90qrrAC.png)

**Comment by aduh95** [comment]
Thank you for spotting that! I am going to investigate this.

I'll edit the issue title as I think it impacts only the class diagrams.

**Comment by 174n** [comment]
Ok, thank you
